export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVEALL_ITEM = "CART_REMOVEALL_ITEM";
export const CART_SUBTRACT_ITEM = "CART_SUBTRACT_ITEM";
export const CART_ADDITION_ITEM = "CART_ADDITION_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVESHIPPING_ADDRESS = "CART_SAVESHIPPING_ADDRESS";
