export const CREATE_WISHLIST_REQUEST = "CREATE_WISHLIST_REQUEST";
export const CREATE_WISHLIST_SUCCESS = "CREATE_WISHLIST_SUCCESS";
export const CREATE_WISHLIST_FAIL = "CREATE_WISHLIST_FAIL";
export const DELETE_WISHLIST_REQUEST = "DELETE_WISHLIST_REQUEST";
export const DELETE_WISHLIST_SUCCESS = "DELETE_WISHLIST_SUCCESS";
export const DELETE_WISHLIST_FAIL = "DELETE_WISHLIST_FAIL";
export const WISHLIST_REMOVE_ITEM = "WISHLIST_REMOVE_ITEM";
